name: "CI"

on:
  push:
    branches:
      - "main"
      - "feat**"
      - "fix**"
    tags-ignore:
      - "**"
  pull_request:

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4.2.2

      - name: "Setup Biome"
        uses: biomejs/setup-biome@v2.3.0

      - name: "Run Biome"
        run: biome ci .

  build:
    name: "Build & Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4.2.2

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v4.0.0

      - name: "Setup node"
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: "Install dependencies"
        run: pnpm install

      - name: "Typecheck"
        run: pnpm run typecheck

      - name: "Run Build"
        run: pnpm run build
